# Code to import and clean data from the Soil Network
# By:  Stephen Teet 
# Import the data file (.csv)
df1 <- read.csv('TOA5_67880.Cosmos_P13_Station16.csv')

# *****Get daily averages using lubridate, tidyverse, and dplyr*****
# Import libraries
library(tidyverse)
library(lubridate)
library(dplyr, warn.conflicts = FALSE)

# Fix Date/Time
df1$TIMESTAMP = mdy_hm(df1$TIMESTAMP, tz = "America/Chicago")

df2 <- data.frame(DateTime = df1$TIMESTAMP,
                  batt_volt = df1$batt_volt,
                  VWC0_Avg = df1$VWC0_Avg,
                  EC0_Avg = df1$EC0_Avg,
                  TSoil0_Avg = df1$TSoil0_Avg,
                  Perm0 = df1$Perm0,
                  PerAvg0 = df1$PerAvg0,
                  VoltR0 = df1$VoltR0,
                  VWC1_Avg = df1$VWC1_Avg,
                  EC1_Avg = df1$EC1_Avg,
                  TSoil1_Avg = df1$TSoil1_Avg,
                  Perm1 = df1$Perm1,
                  PerAvg1 = df1$PerAvg1,
                  VoltR1 = df1$VoltR1,
                  VWC2_Avg = df1$VWC2_Avg,
                  EC2_Avg = df1$EC2_Avg,
                  TSoil2_Avg = df1$TSoil2_Avg,
                  Perm2 = df1$Perm2,
                  PerAvg2 = df1$PerAvg2,
                  VoltR2 = df1$VoltR2,
                  VWC3_Avg = df1$VWC3_Avg,
                  EC3_Avg = df1$EC3_Avg,
                  TSoil3_Avg = df1$TSoil3_Avg,
                  Perm3 = df1$Perm3,
                  PerAvg3 = df1$PerAvg3,
                  VoltR3 = df1$VoltR3,
                  VWC4_Avg = df1$VWC4_Avg,
                  EC4_Avg = df1$EC4_Avg,
                  TSoil4_Avg = df1$TSoil4_Avg,
                  Perm4 = df1$Perm4,
                  PerAvg4 = df1$PerAvg4,
                  VoltR4 = df1$VoltR4,
                  VWC5_Avg = df1$VWC5_Avg,
                  EC5_Avg = df1$EC5_Avg,
                  TSoil5_Avg = df1$TSoil5_Avg,
                  Perm5 = df1$Perm5,
                  PerAvg5 = df1$PerAvg5,
                  VoltR5 = df1$VoltR5,
                  VWC6_Avg = df1$VWC6_Avg,
                  EC6_Avg = df1$EC6_Avg,
                  TSoil6_Avg = df1$TSoil6_Avg,
                  Perm6 = df1$Perm6,
                  PerAvg6 = df1$PerAvg6,
                  VoltR6 = df1$VoltR6,
                  VWC7_Avg = df1$VWC7_Avg,
                  EC7_Avg = df1$EC7_Avg,
                  TSoil7_Avg = df1$TSoil7_Avg,
                  Perm7 = df1$Perm7,
                  PerAvg7 = df1$PerAvg7,
                  VoltR7 = df1$VoltR7,
                  VWC8_Avg = df1$VWC8_Avg,
                  EC8_Avg = df1$EC8_Avg,
                  TSoil8_Avg = df1$TSoil8_Avg,
                  Perm8 = df1$Perm8,
                  PerAvg8 = df1$PerAvg8,
                  VoltR8 = df1$VoltR8,
                  VWC9_Avg = df1$VWC9_Avg,
                  EC9_Avg = df1$EC9_Avg,
                  TSoil9_Avg = df1$TSoil9_Avg,
                  Perm9 = df1$Perm9,
                  PerAvg9 = df1$PerAvg9,
                  VoltR9 = df1$VoltR9)
# Get daily values
df3 <- df2 %>% group_by(DateTime = date(DateTime)) %>%
  summarise(batt_volt = min(batt_volt),
            VWC0_Avg = mean(VWC0_Avg),
            EC0_Avg = mean(EC0_Avg),
            TSoil0_Avg = mean(TSoil0_Avg),
            Perm0 = mean(Perm0),
            PerAvg0 = mean(PerAvg0),
            VoltR0 = mean(VoltR0),
            VWC1_Avg = mean(VWC1_Avg),
            EC1_Avg = mean(EC1_Avg),
            TSoil1_Avg = mean(TSoil1_Avg),
            Perm1 = mean(Perm1),
            PerAvg1 = mean(PerAvg1),
            VoltR1 = mean(VoltR1),
            VWC2_Avg = mean(VWC2_Avg),
            EC2_Avg = mean(EC2_Avg),
            TSoil2_Avg = mean(TSoil2_Avg),
            Perm2 = mean(Perm2),
            PerAvg2 = mean(PerAvg2),
            VoltR2 = mean(VoltR2),
            VWC3_Avg = mean(VWC3_Avg),
            EC3_Avg = mean(EC3_Avg),
            TSoil3_Avg = mean(TSoil3_Avg),
            Perm3 = mean(Perm3),
            PerAvg3 = mean(PerAvg3),
            VoltR3 = mean(VoltR3),
            VWC4_Avg = mean(VWC4_Avg),
            EC4_Avg = mean(EC4_Avg),
            TSoil4_Avg = mean(TSoil4_Avg),
            Perm4 = mean(Perm4),
            PerAvg4 = mean(PerAvg4),
            VoltR4 = mean(VoltR4),
            VWC5_Avg = mean(VWC5_Avg),
            EC5_Avg = mean(EC5_Avg),
            TSoil5_Avg = mean(TSoil5_Avg),
            Perm5 = mean(Perm5),
            PerAvg5 = mean(PerAvg5),
            VoltR5 = mean(VoltR5),
            VWC6_Avg = mean(VWC6_Avg),
            EC6_Avg = mean(EC6_Avg),
            TSoil6_Avg = mean(TSoil6_Avg),
            Perm6 = mean(Perm6),
            PerAvg6 = mean(PerAvg6),
            VoltR6 = mean(VoltR6),
            VWC7_Avg = mean(VWC7_Avg),
            EC7_Avg = mean(EC7_Avg),
            TSoil7_Avg = mean(TSoil7_Avg),
            Perm7 = mean(Perm7),
            PerAvg7 = mean(PerAvg7),
            VoltR7 = mean(VoltR7),
            VWC8_Avg = mean(VWC8_Avg),
            EC8_Avg = mean(EC8_Avg),
            TSoil8_Avg = mean(TSoil8_Avg),
            Perm8 = mean(Perm8),
            PerAvg8 = mean(PerAvg8),
            VoltR8 = mean(VoltR8),
            VWC9_Avg = mean(VWC9_Avg),
            EC9_Avg = mean(EC9_Avg),
            TSoil9_Avg = mean(TSoil9_Avg),
            Perm9 = mean(Perm9),
            PerAvg9 = mean(PerAvg9),
            VoltR9 = mean(VoltR9))

# Write cleaned data table to .csv
write.csv(df3, "P13_Station16_31102023.csv", row.names = FALSE)

# Print last days minimum battery voltage
tail(df3$batt_volt, 1)
